// import type { Metadata } from "next";
import { Mulish } from "next/font/google";
import "./globals.css";
import { Layout } from './context';
import { getNavCollection, getHomePageCollection, getHomeLandingPageCollection, getFooterCollection } from "@/lib/api";
import { draftMode } from "next/headers";
import NavigationBar from "./navigationBar";
import Footer from "./footer";
import FooterLayout from "./footer/footerLayout";
import Home from "./home/page";

const mulish = Mulish({ subsets: ["latin"] });

export const Metadata = {
  title: "Atlantic Credit & Finance",
  description: "Generated by create next app",
};


export default async function RootLayout({children}) {
  const { isEnabled } = draftMode();
  const navData = await getNavCollection(isEnabled);
  const footerData = await getFooterCollection(isEnabled);
  const homePageData = await getHomePageCollection(isEnabled);
  const homeLandingPage = await getHomeLandingPageCollection(isEnabled);
  
  return (
    <html lang="en">
      <body  className={`${mulish.className} max-w-max-width m-[auto] bg-alice-blue`}>
       <main>hello</main>
        <NavigationBar navData={navData[0]} />
           <main>{children}</main>
          {/*{footerData.map((item, index) => {
          return (
            <div key={index}> 
              <FooterLayout data={item} />
            </div>
          ) 
        })} */}
        </body>
    </html>
  );
};


// export default async function RootLayout({
//   children,
// }: 
// Readonly<{
//   children: React.ReactNode;
// }>) 
// {
//   const { isEnabled } = draftMode();
//   const navData = await getNavCollection(isEnabled);
//   const homePageData = await getHomePageCollection(isEnabled);
//   const homeLandingPage = await getHomeLandingPageCollection(isEnabled);
  
//   return (
//     <html lang="en">
//       <body  className={`${mulish.className} max-w-max-width m-[auto] bg-alice-blue`}>
//         <NavigationBar navData={navData[0]} />
//           {/* <Home homeLandingPage={homeLandingPage} homePageData={homePageData} /> */}
//           {children}
//         <Footer />
//         </body>
//     </html>
//   );
// };

