import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { Layout } from './context';
import { getFooterCollection } from "@/lib/api";
import { getNavCollection } from "@/lib/api";
import { draftMode } from "next/headers";
import NavigationBar from "./navigationBar";
import Footer from "./footer";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Atlantic Credit & Finance",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: 
Readonly<{
  children: React.ReactNode;
}>) 
{
  const { isEnabled } = draftMode();
  const navData = await getNavCollection(isEnabled);
  
  return (
    <html lang="en">
      {/* <Layout sharedData={footerData}> */}
        <body className={inter.className}>
          <NavigationBar navData={navData[0]} />
            {children}
            <Footer />
          </body>
      {/* </Layout> */}
    </html>
  );
}  
